run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - deadcode
    - errcheck
    - govet
    - gosimple
    - gofmt
    - goconst
    - golint
    - goimports
    - ineffassign
    - prealloc
    - revive
    - staticcheck
    - unused
linters-settings:
  govet:
    check-shadowing: true
